# Database Credentials
db.driverName = com.mysql.cj.jdbc.Driver
db.connectionString = jdbc:mysql://localhost:3306/shopping-cart
db.username = root
db.password = 4700

#Mailer Credentials
mailer.email=celsofuentes957@gmail.com
mailer.password=nexw hkmg iweu rimg